
target 'WeatherApp' do
  use_frameworks!

  # Pods for WeatherApp
  
  pod 'Alamofire', '~> 4.4'

  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
